= Collections

Personal selection of collection methods

[source,php]
$average = collect([1, 1, 2, 4])->avg(); // 2

[source,php]
$collection = collect([1, 2, 3]);
$chunks = $collection->chunk(2);
$chunks->all(); // [[1,2], [3]]

[source,php]
$collection = collect([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);
$collapsed = $collection->collapse();
$collapsed->all(); // [1, 2, 3, 4, 5, 6, 7, 8, 9]

[source,php]
$collection = collect(['name', 'age']);
$combined = $collection->combine(['George', 29]);
$combined->all(); // ['name' => 'George', 'age' => 29]

[source,php]
$collection = collect(['foo']);
$concatenated = $collection->concat(['bar']);
$concatenated->all(); // ['foo', 'bar']

[source,php]
$collection = collect(['name' => 'Sean');
$collection->contains('Sean'); // true
$collection->contains('name'); // false

[source,php]
$collection = collect(['name' => 'Sean');
$collection->has('name'); // true
$collection->has('Sean'); // false

[source,php]
$collection = collect([1, 2, 3, 4]);
$collection->count(); // 4

[source,php]
$collection = collect([1, 2, 2, 2, 3]);
$counted = $collection->countBy(); // count occurences
$counted->all(); // [1 => 1, 2 => 3, 3 => 1]
// OR exclude occurences
$unique = $collection->unique();
$unique->values()->all(); // [1, 2, 3]

[source,php]
$collection = collect(['John Doe', 'Jane Doe']);
$collection->dd();
/*
    Collection {
        #items: array:2 [
            0 => "John Doe"
            1 => "Jane Doe"
        ]
    }
*/

[source,php]
$collection = collect(['product_id' => 1, 'price' => 100, 'discount' => false]);
$filtered = $collection->except(['price', 'discount']);
$filtered->all(); // ['product_id' => 1]
$filtered = $collection->only(['price']);
$filtered->all(); // ['price' => 100]

[source,php]
$collection = collect([
'name' => 'taylor',
'languages' => [
    'php', 'javascript'
    ]
]);
$flattened = $collection->flatten();
$flattened->all(); // ['taylor', 'php', 'javascript'];

[source,php]
$collection = collect([
['account_id' => 1, 'product' => 'Desk'],
['account_id' => 2, 'product' => 'Chair'],
]);
$collection->implode('product', ', '); // Desk, Chair

[source,php]
$collection = collect(['Desk', 'Sofa', 'Chair']);
$intersect = $collection->intersect(['Desk', 'Chair', 'Bookcase']);
$intersect->all(); // [0 => 'Desk', 2 => 'Chair']

[source,php]
$collection = collect([5, 3, 1, 2, 4]);
$sorted = $collection->sort();
$sorted->values()->all(); // [1, 2, 3, 4, 5]

[source,php]
$collection = collect([
['name' => 'Desk', 'price' => 200],
['name' => 'Chair', 'price' => 100],
['name' => 'Bookcase', 'price' => 150],
]);
$sorted = $collection->sortBy('price');
$sorted->values()->all();
/*
[
    ['name' => 'Chair', 'price' => 100],
    ['name' => 'Bookcase', 'price' => 150],
    ['name' => 'Desk', 'price' => 200],
]
*/

[source,php]
collect([2, 4, 6, 8])->search(function ($item, $key) {
    return $item > 5; // 2
});

[source,php]
$collection = collect(['name' => 'Desk', 'price' => 200]);
$collection->toJson(); // '{"name":"Desk", "price":200}'