= Service Container

Powerfull tool for managing class dependencies and performing dependency injection via the constructor class.
e.g.
[source,php]
public function __construct(UserRepository $users)
{
   $this->users = $users;
}

If a class has no dependencies or only depends on other concrete classes, the container does not need to be instructed on the constructor.

[source,php]
Route::get('/', function (Request $request) {
    // ...
});

In many cases, thanks to automatic dependency injection and facades, you can build Laravel applications without ever manually binding or resolving anything from the container. e.g.
[source,php]
$this->app //in the provider
App::something //out the provider

We can register a binding with this method with 3 differents ways as
normal bind -> new instance at each calls
singleton bind -> same instance at each call
instance bind -> copy an existing instance

[source,php]
$this->app->bind(EventPusher::class, RedisEventPusher::class);

This statement tells the container that it should inject the RedisEventPusher when a class needs an implementation of EventPusher.

If the type hinted class have an another dependency injection which needs params too, you will have to use binding method. e.g.

[source,php]
$this->app->singleton(EventPusher::class, function () {
    return new RedisEventPusherService('argument1', 'argument2');
});